name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal ./Tests/Glav.CognitiveServices.UnitTests/Glav.CognitiveServices.UnitTests.csproj

    - name: Test enironment vars
      env:
        TEST: blah
        run: echo $TEST

    - name: Integration Tests
      env:
        COMPUTERVISION_API_KEY: ${{ secrets.COMPUTERVISIONAPIKEY }}
        FACE_API_KEY: ${{ secrets.FACEAPIKEY }}
        TEXTANALYTIC_API_KEY: ${{ secrets.TEXTANALYTICAPIKEY }}
      run: dotnet test --no-restore --verbosity normal ./Tests/Glav.CognitiveServices.IntegrationTests/Glav.CognitiveServices.IntegrationTests.csproj
      
